FROM node:14.5-alpine

ADD ./start-container /usr/local/bin/start-container

# RUN addgroup -g 1000 laravel
# RUN adduser -G laravel -g laravel -s /bin/sh -D laravel

# RUN chown laravel:laravel /var/www/html

RUN chmod +x /usr/local/bin/start-container
